// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/callback": {
    params: {};
  };
  "/auth/callback/google": {
    params: {};
  };
  "/auth/callback/kakao": {
    params: {};
  };
  "/auth/callback/naver": {
    params: {};
  };
  "/auth/signup": {
    params: {};
  };
  "/auth/signup/terms": {
    params: {};
  };
  "/auth/signup/type": {
    params: {};
  };
  "/auth/signup/info": {
    params: {};
  };
  "/auth/signup/info-more": {
    params: {};
  };
  "/auth/signup/purpose": {
    params: {};
  };
  "/auth/signup/success": {
    params: {};
  };
  "/matching": {
    params: {};
  };
  "/matching/brand": {
    params: {};
  };
  "/matching/campaign": {
    params: {};
  };
  "/matching/suggest": {
    params: {};
  };
  "/matching/suggest/create": {
    params: {};
  };
  "/matching/test": {
    params: {};
  };
  "/matching/test/step1": {
    params: {};
  };
  "/matching/test/step2": {
    params: {};
  };
  "/matching/test/step3": {
    params: {};
  };
  "/matching/test/result": {
    params: {};
  };
  "/business": {
    params: {};
  };
  "/business/calendar": {
    params: {};
  };
  "/business/campaign": {
    params: {};
  };
  "/business/proposal": {
    params: {};
  };
  "/business/rejection": {
    params: {};
  };
  "/chat": {
    params: {};
  };
  "/rooms": {
    params: {};
  };
  "/rooms/:chatId": {
    params: {
      "chatId": string;
    };
  };
  "/mypage": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/auth/login" | "/auth/callback" | "/auth/callback/google" | "/auth/callback/kakao" | "/auth/callback/naver" | "/auth/signup" | "/auth/signup/terms" | "/auth/signup/type" | "/auth/signup/info" | "/auth/signup/info-more" | "/auth/signup/purpose" | "/auth/signup/success" | "/matching" | "/matching/brand" | "/matching/campaign" | "/matching/suggest" | "/matching/suggest/create" | "/matching/test" | "/matching/test/step1" | "/matching/test/step2" | "/matching/test/step3" | "/matching/test/result" | "/business" | "/business/calendar" | "/business/campaign" | "/business/proposal" | "/business/rejection" | "/chat" | "/rooms" | "/rooms/:chatId" | "/mypage" | "/*";
  };
  "routes/auth/route.tsx": {
    id: "routes/auth/route";
    page: "/auth" | "/auth/login" | "/auth/callback" | "/auth/callback/google" | "/auth/callback/kakao" | "/auth/callback/naver" | "/auth/signup" | "/auth/signup/terms" | "/auth/signup/type" | "/auth/signup/info" | "/auth/signup/info-more" | "/auth/signup/purpose" | "/auth/signup/success";
  };
  "routes/auth/login/route.tsx": {
    id: "routes/auth/login/route";
    page: "/auth/login";
  };
  "routes/auth/callback/route.tsx": {
    id: "routes/auth/callback/route";
    page: "/auth/callback" | "/auth/callback/google" | "/auth/callback/kakao" | "/auth/callback/naver";
  };
  "routes/auth/callback/google/route.tsx": {
    id: "routes/auth/callback/google/route";
    page: "/auth/callback/google";
  };
  "routes/auth/callback/kakao/route.tsx": {
    id: "routes/auth/callback/kakao/route";
    page: "/auth/callback/kakao";
  };
  "routes/auth/callback/naver/route.tsx": {
    id: "routes/auth/callback/naver/route";
    page: "/auth/callback/naver";
  };
  "routes/auth/signup/route.tsx": {
    id: "routes/auth/signup/route";
    page: "/auth/signup" | "/auth/signup/terms" | "/auth/signup/type" | "/auth/signup/info" | "/auth/signup/info-more" | "/auth/signup/purpose" | "/auth/signup/success";
  };
  "routes/auth/signup/terms/route.tsx": {
    id: "routes/auth/signup/terms/route";
    page: "/auth/signup/terms";
  };
  "routes/auth/signup/type/route.tsx": {
    id: "routes/auth/signup/type/route";
    page: "/auth/signup/type";
  };
  "routes/auth/signup/info/route.tsx": {
    id: "routes/auth/signup/info/route";
    page: "/auth/signup/info";
  };
  "routes/auth/signup/info-more/route.tsx": {
    id: "routes/auth/signup/info-more/route";
    page: "/auth/signup/info-more";
  };
  "routes/auth/signup/purpose/route.tsx": {
    id: "routes/auth/signup/purpose/route";
    page: "/auth/signup/purpose";
  };
  "routes/auth/signup/success/route.tsx": {
    id: "routes/auth/signup/success/route";
    page: "/auth/signup/success";
  };
  "routes/_main.tsx": {
    id: "routes/_main";
    page: "/" | "/matching" | "/matching/brand" | "/matching/campaign" | "/matching/suggest" | "/matching/suggest/create" | "/matching/test" | "/matching/test/step1" | "/matching/test/step2" | "/matching/test/step3" | "/matching/test/result" | "/business" | "/business/calendar" | "/business/campaign" | "/business/proposal" | "/business/rejection" | "/chat" | "/rooms" | "/rooms/:chatId" | "/mypage";
  };
  "routes/home/index.tsx": {
    id: "routes/home/index";
    page: "/";
  };
  "routes/matching/route.tsx": {
    id: "routes/matching/route";
    page: "/matching" | "/matching/brand" | "/matching/campaign";
  };
  "routes/matching/brand/route.tsx": {
    id: "routes/matching/brand/route";
    page: "/matching/brand";
  };
  "routes/matching/campaign/route.tsx": {
    id: "routes/matching/campaign/route";
    page: "/matching/campaign";
  };
  "routes/matching/suggest/route.tsx": {
    id: "routes/matching/suggest/route";
    page: "/matching/suggest" | "/matching/suggest/create";
  };
  "routes/matching/suggest/index.tsx": {
    id: "routes/matching/suggest/index";
    page: "/matching/suggest";
  };
  "routes/matching/suggest/create/route.tsx": {
    id: "routes/matching/suggest/create/route";
    page: "/matching/suggest/create";
  };
  "routes/matching/test/route.tsx": {
    id: "routes/matching/test/route";
    page: "/matching/test" | "/matching/test/step1" | "/matching/test/step2" | "/matching/test/step3" | "/matching/test/result";
  };
  "routes/matching/test/step1/route.tsx": {
    id: "routes/matching/test/step1/route";
    page: "/matching/test/step1";
  };
  "routes/matching/test/step2/route.tsx": {
    id: "routes/matching/test/step2/route";
    page: "/matching/test/step2";
  };
  "routes/matching/test/step3/route.tsx": {
    id: "routes/matching/test/step3/route";
    page: "/matching/test/step3";
  };
  "routes/matching/test/result/route.tsx": {
    id: "routes/matching/test/result/route";
    page: "/matching/test/result";
  };
  "routes/business/route.tsx": {
    id: "routes/business/route";
    page: "/business" | "/business/calendar" | "/business/campaign" | "/business/proposal" | "/business/rejection";
  };
  "routes/business/calendar/route.tsx": {
    id: "routes/business/calendar/route";
    page: "/business/calendar";
  };
  "routes/business/campaign/route.tsx": {
    id: "routes/business/campaign/route";
    page: "/business/campaign";
  };
  "routes/business/proposal/route.tsx": {
    id: "routes/business/proposal/route";
    page: "/business/proposal";
  };
  "routes/business/rejection/route.tsx": {
    id: "routes/business/rejection/route";
    page: "/business/rejection";
  };
  "routes/chat/route.tsx": {
    id: "routes/chat/route";
    page: "/chat";
  };
  "routes/rooms/route.tsx": {
    id: "routes/rooms/route";
    page: "/rooms" | "/rooms/:chatId";
  };
  "routes/rooms/$chatId.tsx": {
    id: "routes/rooms/$chatId";
    page: "/rooms/:chatId";
  };
  "routes/mypage/route.tsx": {
    id: "routes/mypage/route";
    page: "/mypage";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/auth/route": typeof import("./app/routes/auth/route.tsx");
  "routes/auth/login/route": typeof import("./app/routes/auth/login/route.tsx");
  "routes/auth/callback/route": typeof import("./app/routes/auth/callback/route.tsx");
  "routes/auth/callback/google/route": typeof import("./app/routes/auth/callback/google/route.tsx");
  "routes/auth/callback/kakao/route": typeof import("./app/routes/auth/callback/kakao/route.tsx");
  "routes/auth/callback/naver/route": typeof import("./app/routes/auth/callback/naver/route.tsx");
  "routes/auth/signup/route": typeof import("./app/routes/auth/signup/route.tsx");
  "routes/auth/signup/terms/route": typeof import("./app/routes/auth/signup/terms/route.tsx");
  "routes/auth/signup/type/route": typeof import("./app/routes/auth/signup/type/route.tsx");
  "routes/auth/signup/info/route": typeof import("./app/routes/auth/signup/info/route.tsx");
  "routes/auth/signup/info-more/route": typeof import("./app/routes/auth/signup/info-more/route.tsx");
  "routes/auth/signup/purpose/route": typeof import("./app/routes/auth/signup/purpose/route.tsx");
  "routes/auth/signup/success/route": typeof import("./app/routes/auth/signup/success/route.tsx");
  "routes/_main": typeof import("./app/routes/_main.tsx");
  "routes/home/index": typeof import("./app/routes/home/index.tsx");
  "routes/matching/route": typeof import("./app/routes/matching/route.tsx");
  "routes/matching/brand/route": typeof import("./app/routes/matching/brand/route.tsx");
  "routes/matching/campaign/route": typeof import("./app/routes/matching/campaign/route.tsx");
  "routes/matching/suggest/route": typeof import("./app/routes/matching/suggest/route.tsx");
  "routes/matching/suggest/index": typeof import("./app/routes/matching/suggest/index.tsx");
  "routes/matching/suggest/create/route": typeof import("./app/routes/matching/suggest/create/route.tsx");
  "routes/matching/test/route": typeof import("./app/routes/matching/test/route.tsx");
  "routes/matching/test/step1/route": typeof import("./app/routes/matching/test/step1/route.tsx");
  "routes/matching/test/step2/route": typeof import("./app/routes/matching/test/step2/route.tsx");
  "routes/matching/test/step3/route": typeof import("./app/routes/matching/test/step3/route.tsx");
  "routes/matching/test/result/route": typeof import("./app/routes/matching/test/result/route.tsx");
  "routes/business/route": typeof import("./app/routes/business/route.tsx");
  "routes/business/calendar/route": typeof import("./app/routes/business/calendar/route.tsx");
  "routes/business/campaign/route": typeof import("./app/routes/business/campaign/route.tsx");
  "routes/business/proposal/route": typeof import("./app/routes/business/proposal/route.tsx");
  "routes/business/rejection/route": typeof import("./app/routes/business/rejection/route.tsx");
  "routes/chat/route": typeof import("./app/routes/chat/route.tsx");
  "routes/rooms/route": typeof import("./app/routes/rooms/route.tsx");
  "routes/rooms/$chatId": typeof import("./app/routes/rooms/$chatId.tsx");
  "routes/mypage/route": typeof import("./app/routes/mypage/route.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};