/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainMypageRouteImport } from './routes/_main/mypage'
import { Route as MainMatchingRouteImport } from './routes/_main/matching'
import { Route as MainChatRouteImport } from './routes/_main/chat'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainMypageRoute = MainMypageRouteImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => MainRoute,
} as any)
const MainMatchingRoute = MainMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => MainRoute,
} as any)
const MainChatRoute = MainChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => MainRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/chat': typeof MainChatRoute
  '/matching': typeof MainMatchingRoute
  '/mypage': typeof MainMypageRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/chat': typeof MainChatRoute
  '/matching': typeof MainMatchingRoute
  '/mypage': typeof MainMypageRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_main/chat': typeof MainChatRoute
  '/_main/matching': typeof MainMatchingRoute
  '/_main/mypage': typeof MainMypageRoute
  '/_main/': typeof MainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/chat' | '/matching' | '/mypage' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/chat' | '/matching' | '/mypage' | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_auth/login'
    | '/_main/chat'
    | '/_main/matching'
    | '/_main/mypage'
    | '/_main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/mypage': {
      id: '/_main/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof MainMypageRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/matching': {
      id: '/_main/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof MainMatchingRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/chat': {
      id: '/_main/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof MainChatRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainRouteChildren {
  MainChatRoute: typeof MainChatRoute
  MainMatchingRoute: typeof MainMatchingRoute
  MainMypageRoute: typeof MainMypageRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainChatRoute: MainChatRoute,
  MainMatchingRoute: MainMatchingRoute,
  MainMypageRoute: MainMypageRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
